version: '3.8'

services:
  microservice1:
    build:
      context: ./microservice1  # Path to the Dockerfile for microservice1
      dockerfile: Dockerfile     # You can specify the exact Dockerfile name if it's not default
    ports:
      - "8081:80"  # Mapping container port 80 to host port 8081
    networks:
      - app-network

  microservice2:
    build:
      context: ./microservice2  # Path to the Dockerfile for microservice2
      dockerfile: Dockerfile     # You can specify the exact Dockerfile name if it's not default
    ports:
      - "8082:80"  # Mapping container port 80 to host port 8082
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Default network for communication between microservices
